alias: Add alias for non-password SSH sessions
When using ssh with PasswordAuthentication but it is not preferred.
So ssh will fail cause it tried to connect by ssh-key as the
following error:

    error: maximum authentication attempts exceeded